"""initial schema

Revision ID: 9ece72069e1f
Revises: 
Create Date: 2026-07-30 08:02:00.570343
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9ece72069e1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('collection', sa.String(length=128), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=2048), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_log_collection'), ['collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_log_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_log_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_alert_sent_at', ['sent_at'], unique=False)

    op.create_table('floor_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.Column('collection', sa.String(length=128), nullable=False),
    sa.Column('floor_ton', sa.Float(), nullable=False),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.String(length=128), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('floor_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_floor_collection_time', ['collection', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_floor_snapshots_collection'), ['collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_floor_snapshots_venue'), ['venue'], unique=False)
        batch_op.create_index('ix_floor_venue_collection_time', ['venue', 'collection', 'captured_at'], unique=False)

    op.create_table('routed_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.Column('collection', sa.String(length=128), nullable=False),
    sa.Column('listing_id', sa.String(length=128), nullable=False),
    sa.Column('price_ton', sa.Float(), nullable=False),
    sa.Column('fee_ton', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routed_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routed_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_routed_trades_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index('ix_trade_status_time', ['status', 'created_at'], unique=False)

    op.create_table('sale_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.Column('collection', sa.String(length=128), nullable=False),
    sa.Column('gift_id', sa.String(length=128), nullable=False),
    sa.Column('price_ton', sa.Float(), nullable=False),
    sa.Column('buyer', sa.String(length=96), nullable=False),
    sa.Column('seller', sa.String(length=96), nullable=False),
    sa.Column('onchain', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue', 'gift_id', 'occurred_at', name='uq_sale_identity')
    )
    with op.batch_alter_table('sale_events', schema=None) as batch_op:
        batch_op.create_index('ix_sale_collection_time', ['collection', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_events_collection'), ['collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_events_venue'), ['venue'], unique=False)

    op.create_table('service_heartbeat',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('wallet_address', sa.String(length=96), nullable=False),
    sa.Column('referred_by', sa.String(length=64), nullable=False),
    sa.Column('vip_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('collection', sa.String(length=128), nullable=False),
    sa.Column('target_ton', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'collection', name='uq_watch_user_collection')
    )
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watches_collection'), ['collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_telegram_id'), ['telegram_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watches_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_watches_collection'))

    op.drop_table('watches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    op.drop_table('service_heartbeat')
    with op.batch_alter_table('sale_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_events_venue'))
        batch_op.drop_index(batch_op.f('ix_sale_events_collection'))
        batch_op.drop_index('ix_sale_collection_time')

    op.drop_table('sale_events')
    with op.batch_alter_table('routed_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trade_status_time')
        batch_op.drop_index(batch_op.f('ix_routed_trades_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_routed_trades_status'))

    op.drop_table('routed_trades')
    with op.batch_alter_table('floor_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_floor_venue_collection_time')
        batch_op.drop_index(batch_op.f('ix_floor_snapshots_venue'))
        batch_op.drop_index(batch_op.f('ix_floor_snapshots_collection'))
        batch_op.drop_index('ix_floor_collection_time')

    op.drop_table('floor_snapshots')
    with op.batch_alter_table('alert_log', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_sent_at')
        batch_op.drop_index(batch_op.f('ix_alert_log_kind'))
        batch_op.drop_index(batch_op.f('ix_alert_log_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_alert_log_collection'))

    op.drop_table('alert_log')
    # ### end Alembic commands ###
